feat: Add ByteDance effect RTE extensions demo
AgoraIO-Community/AgoraMarketplace pull request #1
Opened 2022-01-10 09:41 UTC by littleGnAl

2022-01-10 09:45 UTC, LichKing-2234 requested changes

2022-01-10 09:45 UTC, LichKing-2234 commented on ByteDance/android/app/src/main/java/io/agora/rte/extension/bytedance/example/MainActivity.java
> +        "byte_dance/LicenseBag.bundle/agora_test_20211216_20220316_io.agora.rte.extension.bytedance_4.2.3.licbag");
这个也做成配置项，不要放到demo中

2022-01-10 09:46 UTC, LichKing-2234 requested changes

2022-01-10 09:46 UTC, LichKing-2234 commented on ByteDance/ios/AgoraByteDanceExtensionDemo/BDResourceHelper.m
> +static NSString *LICENSE_NAME = @"/agora_test_20211216_20220316_io.agora.rte."
这个做成配置项

2022-01-10 09:57 UTC, littleGnAl commented on ByteDance/android/app/src/main/java/io/agora/rte/extension/bytedance/example/MainActivity.java
> +        "byte_dance/LicenseBag.bundle/agora_test_20211216_20220316_io.agora.rte.extension.bytedance_4.2.3.licbag");
@LichKing-2234 Updated.

2022-01-10 09:57 UTC, littleGnAl commented on ByteDance/ios/AgoraByteDanceExtensionDemo/BDResourceHelper.m
> +static NSString *LICENSE_NAME = @"/agora_test_20211216_20220316_io.agora.rte."
@LichKing-2234 Updated.

2022-01-17 06:01 UTC, LichKing-2234 approved these changes

2022-01-18 04:01 UTC, merged